server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer : org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      delay-levels:
        immediate: 0    # 立即处理
        short_10s: 10   # 10秒延迟
        medium_1m: 60   # 1分钟延迟
        long_1h: 3600   # 1小时延迟
      admin:
        auto-create: true # 自动创建Topic

missyou:
  security:
    jwt-key: xue666
    token-expired-in: 7200
  mysql:
    ip: 192.168.56.10
    port: 3307

  order:
    max-sku-limit: 999
    pay-time-limit: 1800
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify

rocketmq:
  producer:
    name-server-addr: localhost:9876
    group-name: test-group
  consumer:
    name-server-addr: localhost:9876
    group-name: test-group