server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired

missyou:
  security:
    jwt-key: xue666
    token-expired-in: 7200
  mysql:
    ip: 192.168.56.10
    port: 3307

  order:
    max-sku-limit: 999
    pay-time-limit: 1800
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify


